import "./globals.css";
import { StateProvider } from "@/context/stateContext";
import reducer, { initialState } from "@/context/stateReducers";

export const metadata = {
  title: "SayHi",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {/* <StateProvider initialState={initialState} reducer={reducer}> */}
        {children}
        {/* </StateProvider> */}
      </body>
    </html>
  );
}
