import "./globals.css";
import { StateProvider } from "@/context/stateContext";

export const metadata = {
  title: "SayHi",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <StateProvider>{children}</StateProvider>
        <div id="photoPickerElement"></div>
      </body>
    </html>
  );
}
